apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-deployment
  labels:
    app.name: helloworld
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.name: helloworld
  template:
    metadata:
      labels:
        app.name: helloworld
    spec:
      containers:
      - name: helloworld-container
        image: ubercadence/helloworld:0.0.1
        imagePullPolicy: "IfNotPresent"
        env:
        - name: HOSTANDPORT
          value: {{ .Values.environmentVar.HostAndPort }}
        - name: DOMAIN
          value: {{ .Values.environmentVar.Domain }}
        - name: SERVICE
          value: {{ .Values.environmentVar.Service }}
      ports:
      - name: helloworld
        conainerPort: 8000
        protocol: TCP
    volumes:
    - name: helloworld